data <- read.csv("household_power_consumption.txt",colClasses=c("character","character",rep("double",7)),header=TRUE,stringsAsFactors=FALSE,sep=";",na.strings=c("?","NA"))
data$Date <- as.Date(data$Date,"%d/%m/%Y")
my_data <- subset(data,data$Date==as.Date("2007-02-01","%Y-%m-%d")|data$Date==as.Date("2007-02-02","%Y-%m-%d"))
my_data$DTTM <- strptime(paste(my_data$Date,my_data$Time),format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(1,1))
with(my_data,plot(DTTM,Sub_metering_1,type="l",col="Black",xlab="",ylab="Energy Sub Metering"))
with(my_data,points(DTTM,Sub_metering_2,type="l",col="Red"))
with(my_data,points(DTTM,Sub_metering_3,type="l",col="Blue"))
legend("topright",pch="-",lwd=4,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()
